baseURL = "https://barsimarina.hu/"
defaultContentLanguage = "hu"
title = "Underdog Guild"

[markup.goldmark.renderer]
unsafe = true
hardWraps = true

[params]
email = "hello@barsimarina.hu"

[languages]

[languages.hu]
languageCode = "hu"
languageName = "Magyar"
title = "Underdog Guild"
weight = 1

[languages.hu.params]
description = "Egyedi, gyors és akadálymentes statikus weboldalak."
ogLocale = "hu_HU"

[languages.en]
languageCode = "en"
languageName = "English"
title = "Underdog Guild"
weight = 2

[languages.en.params]
description = "Unique, fast and accessible static websites."
ogLocale = "en_US"

[languages.en.permalinks]
werkblog = "/werkblog/:slug/"